### ISSUE TITLE
Some confusion about the UV_map_Generator

### ISSUE THREAD

**Issue by EAST-J** [boycehbz/Pose2UV#1]
Hi, thx for your great work. I wonder what's the meaning of the index t1 and t2 in the UV_map_Generator? Moreover, what's the difference between the refine_vts and the vts? How to get the refine_vts?

**Comment by boycehbz** [comment]
The indices t1 and t2 were previously used for calculating the loss, but they can be removed now. Sorry, I haven't completely cleaned up all the code.
'refine_vts' represents the UV coordinates, which can be obtained from the SMPL UV coordinates map.
